locale = 'pt-BR'
defaultContentLanguage = 'pt-br'
title = 'Herdeiros da Vanguarda'
disableKinds = ['taxonomy', 'term', 'rss']
enableRobotsTXT = true

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[outputs]
  home = ['HTML']
  section = ['HTML']
  page = ['HTML']

[minify]
  minifyOutput = true
